"""AI Analytics Copilot page: chat interface grounded in real pipeline data."""
import sys
from pathlib import Path

import streamlit as st

sys.path.append(str(Path(__file__).resolve().parents[2]))
from ai_copilot.copilot import ask
from src.config import OPENAI_API_KEY

SAMPLE_QUESTIONS = [
    "Which customer segment is most profitable?",
    "How much revenue is at risk?",
    "What are the biggest churn drivers?",
    "Which customers should the sales team contact?",
    "Which region has the highest churn?",
    "What should marketing do next month?",
    "Show me the top 10 high-value customers at risk.",
]


def render():
    st.title("🤖 AI Analytics Copilot")
    st.caption(
        "Ask business questions about NovaMart's customers, revenue, and churn. "
        "Answers are grounded in the actual pipeline output -- never invented."
    )

    if OPENAI_API_KEY:
        st.success("LLM backend configured -- answers are generated by an LLM grounded in pipeline data.")
    else:
        st.info(
            "No OPENAI_API_KEY configured -- using the deterministic fallback assistant "
            "(still fully grounded in real pipeline output, just rule-based instead of LLM-generated). "
            "Add a key to .env to enable free-form LLM answers."
        )

    st.markdown("**Try a sample question:**")
    cols = st.columns(3)
    for i, sq in enumerate(SAMPLE_QUESTIONS):
        if cols[i % 3].button(sq, key=f"sample_{i}"):
            st.session_state["copilot_question"] = sq

    question = st.text_input(
        "Your question",
        value=st.session_state.get("copilot_question", ""),
        placeholder="e.g. Which customer segment is most profitable?",
    )

    if st.button("Ask", type="primary") and question.strip():
        with st.spinner("Analyzing..."):
            result = ask(question)
        st.markdown(f"**Answer** _(via {result['backend']})_:")
        st.write(result["answer"])
        if "error" in result:
            with st.expander("Debug: LLM error detail"):
                st.code(result["error"])
